run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - cmd/demo
    - cmd/i18ntool
    - data
    - locale
    - docs
    - ui
    - .git

  skip-files:
    - pkg/utils/terminal.go

linters:
  enable:
    - govet
    - staticcheck

