run:
  timeout: 5m
  modules-download-mode: readonly

issues:
  exclude-dirs:
    - cmd/demo
    - cmd/i18ntool
    - data
    - locale
    - docs
    - ui
    - .git

  exclude-files:
    - pkg/utils/terminal.go

linters:
  enable:
    - govet
    - staticcheck

output:
  formats:
    - format: colored-line-number