ARG VERSION=dev

FROM jumpserver/koko:${VERSION}-ce
ARG TARGETARCH

ARG DEPENDENCIES="                    \
        curl                          \
        git                           \
        git-lfs                       \
        iputils-ping                  \
        openssh-client                \
        telnet                        \
        unzip                         \
        vim                           \
        wget                          \
        xz-utils"

ARG APT_MIRROR=http://deb.debian.org

RUN set -ex \
    && sed -i "s@http://.*.debian.org@${APT_MIRROR}@g" /etc/apt/sources.list.d/debian.sources \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${DEPENDENCIES} \
    && apt-get clean
