ARG VERSION

FROM registry.fit2cloud.com/jumpserver/koko:${VERSION}-ce
ARG TARGETARCH

ARG DEPENDENCIES="                    \
        bash-completion               \
        curl                          \
        git                           \
        git-lfs                       \
        iputils-ping                  \
        jq                            \
        less                          \
        openssh-client                \
        telnet                        \
        unzip                         \
        vim                           \
        wget                          \
        xz-utils"

RUN --mount=type=cache,target=/var/cache/apt,sharing=locked,id=koko \
    --mount=type=cache,target=/var/lib/apt,sharing=locked,id=koko \
    set -ex \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${DEPENDENCIES} \
    && apt-get clean
